service: lambda-exec-awscli

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'} # Set the default stage used. Default is dev
  region: us-east-1
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-identity:*
      Resource: "*"
    - Effect: Allow
      Action:
        - cognito-idp:*
      Resource: "*"

functions:
  getClientSecret:
    handler: src/getClient.getClientSecret
    events:
      - http:
          path: poolId/{poolId}/clientId/{clientId}
          method: GET

  createAppClient:
    handler: src/createClient.createAppClient
    events:
      - http:
          path: createAppClients
          method: POST
        